### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by jonathanmtran** [Jasig/NotificationPortlet#116]
**Describe the bug**
A `regeneratorRuntime is not defined` is preventing the modal notification from rendering

**To Reproduce**
1. Deploy portlet with a modal notification web component such as jasig/uPortal-start#226
2. Open developer tools
3. Navigate to the page containing the modal notification web component

**Expected behavior**
A notification modal

**Screenshots**
![screenshot from 2018-10-04 14-33-13](https://user-images.githubusercontent.com/41875/46504386-a59f0a80-c7e2-11e8-8512-09ddc364c8c0.png)

![screenshot from 2018-10-04 14-32-43](https://user-images.githubusercontent.com/41875/46504397-aafc5500-c7e2-11e8-91cc-3f04e8b66a2a.png)

**Platform:**
 - Notification Portlet Version: 4.3.1
 - Browser: Chrome/ium and Firefox

**Comment by ChristianMurphy** [comment]
![](https://i.imgflip.com/2jeusk.jpg)

**Comment by ChristianMurphy** [comment]
Looking into this now

**Comment by ChristianMurphy** [comment]
@jonathanmtran a work around is adding `<script src="https://unpkg.com/regenerator-runtime@0.12.1/runtime.js"></script>`
https://github.com/uPortal-contrib/uPortal-web-components/issues/117 will probably be the long term fix to prevent this from coming up again as new components get added.

**Comment by jonathanmtran** [comment]
Adding `<script src="https://unpkg.com/regenerator-runtime@0.12.1/runtime.js"></script>` works for Chrome/ium
On the other hand, the modal doesn't render on Firefox

**Comment by ChristianMurphy** [comment]
What version of notification are you using?

That should have been fixed when https://github.com/Jasig/NotificationPortlet/blob/e673a002469ecb3179afcf7eb3692814520e555d/notification-portlet-webcomponents/notification-modal/src/components/NotificationModal.vue#L179-L183

was added in https://github.com/Jasig/NotificationPortlet/commit/dcd0f11c88e70e2b360cec62615d115e07329388 included in v4.3.1+

**Comment by ChristianMurphy** [comment]
Is it still happening in 4.3.1 on your system?

**Comment by jonathanmtran** [comment]
@ChristianMurphy Yes. I've deployed 4.3.1 and it still doesn't render/appear on Firefox

**Comment by ChristianMurphy** [comment]
@jonathanmtran I tested this with uPortal 5.3.0 and a snapshot of the `master` branch of this repo (soon to be officially released).
I'm seeing it work on Chrome, Firefox, and Edge.

Let me know if you run into any other issues, we could hop on a video call and debug.

**Comment by ChristianMurphy** [comment]
Notification portlet 4.4.0 includes the fixes
