### ISSUE TITLE
Modal web component sends user away even though the action is ReadAction

### ISSUE THREAD

**Issue by jonathanmtran** [Jasig/NotificationPortlet#117]
**Describe the bug**
When the modal (web component) has `ReadAction` as one of its available actions, clicking the button would send the user to `/NotificationPortlet/api/v2/action/ReadAction/modal-005?_csrf=...` 

```json
{
  "categories": [
    {
      "title": "Portal Message",
      "entries": [
        {
          "id": "modal-005",
          "priority": 1,
          "title": "Student Portal Updates",
          "body": "Welcome to the new student portal based on <a href=\"https://apereo.org/projects/uPortal\">uPortal 5</a>. There are several exciting new features included with this update. Please take a moment to familiarize yourself with the new content & options.",
          "source": "Demo Service",
          "url": "http:\/\/library.university\/parking",
          "availableActions": [
            {
              "label": "Acknowledge",
              "clazz": "org.jasig.portlet.notice.action.read.ReadAction"
            }
          ]
        }
      ]
    }
  ]
}
```

**Expected behavior**
Fire the action in the background and hide the modal

**Comment by drewwills** [comment]
@jonathanmtran et al.,

The action needs to have the ability to send the user somewhere else.  If the page (and even a `<form>` within it) are entirely submitted, that's easy to do with a server-side HTTP redirect.

It would be possible to do it "in the background" (with JavaScript), but the complexity goes up quite a bit.  We would have to teach the modal component to look for something in the server's response signalling a URL change and then follow it.  We would also have to teach the server-side components to send such a signal.

**Comment by jonathanmtran** [comment]
>We would have to teach the modal component to look for something in the server's response signalling a URL change and then follow it.

In the portlet-based modal, the JavaScript looks for an attribute called `org.jasig.portlet.notice.action.AJAX` and add a `data-ajax` attribute to the action button 

https://github.com/Jasig/NotificationPortlet/blob/e673a002469ecb3179afcf7eb3692814520e555d/notification-portlet-webapp/src/main/webapp/scripts/modal-notice.js#L121-L124

and when the action button is clicked/tapped, it uses that attribute to figure out what how to proceed

https://github.com/Jasig/NotificationPortlet/blob/e673a002469ecb3179afcf7eb3692814520e555d/notification-portlet-webapp/src/main/webapp/scripts/modal-notice.js#L74-L84

Is this approach desirable with the web component ?

**Comment by bjagg** [comment]
@jonathanmtran I think I'm resolving this as part of #330
