### ISSUE TITLE
[Icon web component] Bootstrap stylesheet affects the entire page on Firefox

### ISSUE THREAD

**Issue by jonathanmtran** [Jasig/NotificationPortlet#125]
**Describe the bug**
The Bootstrap stylesheet that is loaded for the icon web component is affecting the entire page as opposed to just the web component

**To Reproduce**
1. Deploy jasig/uPortal-start@ceaf941
2. Removed waffle menu (it prevents the icon from loading on Firefox unless you bump the version to 1.13.5)
3. Log in and observe. You will see that the eyebrow goes from the right to left and that the font sizes shrink once the stylesheet loads

**Screenshots**
![screenshot from 2018-10-15 08-54-10](https://user-images.githubusercontent.com/41875/46962407-ed7e2700-d057-11e8-9e93-d67b79266a94.png)

**Platform:**
 - uPortal Version: 5.3.0
- Notification Portlet: 4.0.0
 - Browser: Firefox 62.0.3

**Comment by ChristianMurphy** [comment]
Firefox less than or equal to version 62 do not support Shadow DOM, meaning the stylesheet can bleed out.
Firefox 63 (to be released 2018-10-23) and above have Shadow DOM enabled by default https://blog.nightly.mozilla.org/2018/09/06/developer-tools-support-for-web-components-in-firefox-63/

My first inclination would be to wait a week for Firefox to add support.
I'm open to other solutions.

**Comment by jonathanmtran** [comment]
I feel that something has to be figured out to support pre-Firefox 63 as the current Firefox ESR is Firefox 60 (ESR)

I pulled the latest beta of Firefox 63 and I'm now seeing huge icons

![screenshot from 2018-10-15 09-23-39](https://user-images.githubusercontent.com/41875/46964293-9464c200-d05c-11e8-9a0c-9dc1c56a0ecc.png)

**Comment by ChristianMurphy** [comment]
> Firefox ESR is Firefox 60 (ESR)

Currently Firefox ESR is not part of the browser support matrix.
https://jasig.github.io/uPortal/SUPPORTED_BROWSERS.html
If it is being used by Universities, it may be something worth considering adding to the matrix.

> I feel that something has to be figured out to support

What do you mean by "support"?
From what you've described, the styles are a bit off, but the page is still fully functional.

> I pulled the latest beta of Firefox 63 and I'm now seeing huge icons

Aha, that looks familiar, I'll apply the patch from form builder here as well.
https://github.com/uPortal-contrib/form-builder/pull/57

**Comment by jonathanmtran** [comment]
> Currently Firefox ESR is not part of the browser support matrix.
> https://jasig.github.io/uPortal/SUPPORTED_BROWSERS.html
> If it is being used by Universities, it may be something worth considering adding to the matrix.

Last time I jumped on a computer I have no install abilities on, it was what's running.

> What do you mean by "support"?
> I want to make sure we're on the same page, so we can get this resolved slightly_smiling_face
> From what you've described, the styles are a bit off, but the page is still fully functional.
> To me, "support" means the webpage looks good in the latest version of Evergreen browsers (Chrome, Firefox, Edge), and functions (but may not be pixel perfect) on the rest of the supported browsers.

That (the styles) is what I'm referring to as well but the problem seems to be a lot trickier (to me at least) when we throw Shadow DOM into the picture

**Comment by ChristianMurphy** [comment]
> > Currently Firefox ESR is not part of the browser support matrix.
> > https://jasig.github.io/uPortal/SUPPORTED_BROWSERS.html

> Last time I jumped on a computer I have no install abilities on, it was what's running.

@drewwills @bjagg @apetro @jgribonvald @mairi thoughts? :thought_balloon: 

> That (the styles) is what I'm referring to as well but the problem seems to be a lot trickier (to me at least) when we throw Shadow DOM into the picture

To each their own.
I'd offer a contrary opinion.
uPortal has had plenty of issues with cascading styles unexpectedly breaking unrelated parts of the portal.
To me Shadow DOM is a solution, not a problem.

In terms of backward compatibility, looking into why https://github.com/webcomponents/shadydom does not seem to be taking affect.

**Comment by ChristianMurphy** [comment]
It looks like to emulate the affect on CSS we'd need to use https://github.com/webcomponents/shadycss, looking into that now.

**Comment by drewwills** [comment]
This is a tough issue.  It's easy to imagine there will be community members (or community institutions) with very strong opinions on either side of this debate.

On the one hand, it's not sustainable to carry on building front-end components with JSR-286, JSPs, and jQuery.  Recent experience has made it very clear to us that our most innovative & prolific contributors are not interested in engaging this kind of work any longer.  These older tools, moreover, are not as good for producing a contemporary-looking, contemporary-feeling UI... they simply don't produce the same quality of outcome.

On the other hand, support for the technologies that power Web Components (our only reasonable alternative to JSR-286) is currently a moving target in the major browsers.  It's hard simply to support the most recent version of all the browsers, and even harder to extend that support to multiple versions of those browsers.

What about this perspective...
  - Working on the Firefox ESR (or similar release of another browser) is something we value
  - But there _is/should be_ no policy that says a contributed component _must_ work on Firefox 60 to be accepted
  - Those that need a component to work on Firefox 60 should pitch in troubleshooting it
  - Once a component has been enhanced to work on Firefox 60, other developers should not contribute changes that break support for Firefox 60 (until it is no longer needed)

**Comment by jgribonvald** [comment]
I'm working mainly on Firefox nigthly building and I didn't get these problems, but I had a similar problem with the eyebrow-user-info, and I solved it with CSS module described https://vue-loader.vuejs.org/guide/css-modules.html#usage, I didn't applyed it on esco-content-menu due to time and as I didn't find any issue on most used browser + Firefox nigthly, but I'm using all components on a fixed position of the body.

On an other part ShaddyDom is not adviced with the Web-component wrapper (if I remmenber well) of vue-js...

With my Firefox version the only problem encountered is with datalist + wc and I opened an issue on Firefox bugzilla. 
I can provide all links tomorrow if you need.

**Comment by jgribonvald** [comment]
To solve the problem on notification-icon you should set the width as component property with a default one (32px should be good).

You have the same problem with waffle menu.

**Comment by jgribonvald** [comment]
The fix is simple, set on .svg-inline--fa a heigth and width with real units or set the parent element size and apply a %. As web-components I would suggest to add a prop that permit to set the size on the parent element and set into .svg-inline--fa height to 80% and width to 80%. This will also fix problems on safari. (It's what I've applied on my web-components and it's working)

**Comment by ChristianMurphy** [comment]
> The fix is simple, set on .svg-inline--fa a heigth and width with real units or set the parent element size and apply a %.

That fixes the height issue with the icon.
That doesn't resolve the issue of styles from in the component bleeding out on to the page.

**Comment by jgribonvald** [comment]
> That doesn't resolve the issue of styles from in the component bleeding out on to the page.

True and for that you need to apply scoped css. I can't say exactly for react but you have a similar build process that help to produce scoped css, with CSS Module, maybe a [good link](https://github.com/gajus/react-css-modules)

**Comment by ChristianMurphy** [comment]
Create React App (CRA) v1 doesn't play well with custom CSS loaders, it's getting better in CRA v2, but we need more flexibility than even CRA v2 offers to get the CSS inside the shadow dom.
I'm currently working to convert this component to Vue so we can leverage scoped styles in a web component friendly way.
