### ISSUE TITLE
[notification-icon-component] Show title in list of notifications as opposed to the body

### ISSUE THREAD

**Issue by jonathanmtran** [Jasig/NotificationPortlet#236]
In https://github.com/Jasig/NotificationPortlet/blob/master/notification-portlet-webcomponents/notification-icon/src/components/NotificationItem.vue#L2, the icon is currently showing the body of the notification

Would it be possible for this to be configurable?

**Comment by drewwills** [comment]
IMHO it should always be the title.

The body is an optional field.

**Comment by bjagg** [comment]
Would be great to get this change in a PR, reviewed and merged today. I would like to cut a new release by Monday morning

**Comment by jonathanmtran** [comment]
Pull request #238 has been submitted for this. This seemed too easy, so let me know if I missed something

**Comment by drewwills** [comment]
I'm sure it's as easy as it looks.  :)
