### ISSUE TITLE
Soffit JWT signature key is never read from uPortal.properties so reverts to default.

### ISSUE THREAD

**Issue by laurenra7** [Jasig/NotificationPortlet#254]
The SIGNATURE_KEY_PROPERTY (org.apereo.portal.soffit.jwt.signatureKey) in [SecurityConfiguration.java](https://github.com/Jasig/NotificationPortlet/blob/a7053a632c9f079e2b055197f0d3d15b43fa2a16/notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/security/SecurityConfiguration.java#L57) is never read from the uPortal.properties file so it always reverts to the default. This causes notifications to not be read into the notification icon if the signatureKey is changed in uPortal.properties.

It looks like the setup is sort of mimicking the way it's set up in the uPortal project (which works), using the [AbstractJwtService](https://github.com/Jasig/uPortal/blob/e4253f72f6ced9738faf7c44fe228379fde7dbd3/uPortal-soffit/uPortal-soffit-core/src/main/java/org/apereo/portal/soffit/service/AbstractJwtService.java#L49), but in the uPortal project the AbstractJwtService is extended in other classes (like [PortalRequestService](https://github.com/Jasig/uPortal/blob/e4253f72f6ced9738faf7c44fe228379fde7dbd3/uPortal-soffit/uPortal-soffit-core/src/main/java/org/apereo/portal/soffit/service/PortalRequestService.java#L30-L31)) which are annotated with @&#8203;Service.

**Comment by jonathanmtran** [comment]
I don't think NotificationPortlet looks at uPortal.properties (https://github.com/Jasig/NotificationPortlet/blob/master/notification-portlet-webapp/src/main/resources/context/applicationContext.xml) so signatureKey would need to be set in global.properties or in notification.properties in order for NotificationPortlet to be aware of it.

**Comment by laurenra7** [comment]
Thank you for pointing that out. I tried global.properties and it worked. Obviously notification.properties would work as well. Probably should be documented...
