### ISSUE TITLE
notification-portlet-webapp-jar not available in Maven Central

### ISSUE THREAD

**Issue by jonathanmtran** [Jasig/NotificationPortlet#358]
I'm trying to build a jar to make some functionality (pull request #352) available but I'm unable to bring in `notification-portlet-webapp-jar` as a dependency.

I see it at https://repo1.maven.org/maven2/org/jasig/portlet/notification/notification-portlet-webapp/4.6.1/ but I'm guessing that since a pom doesn't exist for it, Maven/Grade can't pull it in.

**Comment by bjagg** [comment]
I see the pom.Closing this. @jonathanmtran let me know if you run into this issue still or in the latest release.
